const ReturnCodes = {
  // GENERAL RETURN CODES
  SUCCESS: 0,
  ERROR: 1,
  NOT_FOUND: 2,

  // REQ. BODY CODES
  NOT_A_NUMBER: 10,
  NOT_A_STRING: 11,
  NOT_AN_ARRAY: 12,

  // REQ. QUERY CODES
  Q_INVALID: 20,
  Q_EMPTY: 21,
  Q_NAME: 22,
  Q_TYPE: 23,

  // ID CODES
  INVALID_ID: 30,
  VALID_ID: 31,
  ORIGINAL_ID: 32,

  // AUTHENTICATION CODES
  INVALID_PASSWORD: 40,

  // ENTRY RETURN CODES
  INVALID_POKEMON_TYPE: 50,
  DUPLICATE_ENTRY: 51,
}

module.exports = {
  ReturnCodes
}